# Generated by Django 5.0.3 on 2024-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_in_bank", models.CharField(max_length=20)),
                ("Account_no", models.BigIntegerField()),
                ("ifsc_code", models.CharField(max_length=20)),
                ("Location", models.TextField(blank=True)),
            ],
        ),
    ]
