# Generated by Django 5.0.3 on 2024-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_app", "0003_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.CharField(
                choices=[
                    ("popular", "Popular"),
                    ("technology", "Technology"),
                    ("design", "Design"),
                ],
                default="Tech",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(),
        ),
    ]
